### ISSUE TITLE
Allocation size of info vectors

### ISSUE THREAD

**Issue by andreasdoll** [mpf/spgl1#5]
I'm wondering why the [allocation of info vectors](https://github.com/mpf/spgl1/blob/master/spgl1.m#L274-L277) is done with `min(maxIts, 10000)` instead of just `maxIts`. Is there another reason besides preventing the (possible unnecessary) allocation of huge vectors for large `m=length(b)`?

**Comment by mpf** [comment]
The `min` is there to prevent unreasonably large allocations. For some users of SPGL1, `m` can be enormous.

**Comment by andreasdoll** [comment]
Ok, thanks for clarifying!
