### ISSUE TITLE
Solve 0.5 * || A x - b ||^2 + \lambda || x ||_1

### ISSUE THREAD

**Issue by RoyiAvital** [mpf/spgl1#6]
Hello,

Could you add a solver for L1 Regularized LS - 0.5 * || A x - b ||^2 + \lambda || x ||_1.  
I know there for any Lambda there is a Tau in the Lasso Model s. t. the result is identical.

Yet still it is hard to figure it out and more importantly it would be nice to solve it directly.
It would be great to have it both for the Real and Complex domain.

Thank You.

P. S.
The strange thing regarding this problem is that it seems Proximal Subgradient and Sub Gradient Method are having real hard time when Lambda is very small (While Fixed Point Method will do it easily).

**Comment by mpf** [comment]
There isn't a direct path for applying the SPGL1 algorithm to this problem formulation.
